# Generated by Django 2.2.12 on 2020-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='apellidoPaterno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
